services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    mem_limit: '1g'

  kafka:
    image: confluentinc/cp-server:7.3.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: kafka:29092
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
    mem_limit: '1g'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: kafka:29092
      SCHEMA_REGISTRY_LISTENER_HTTP_PORT: 8081
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

  ksqldb:
    image: confluentinc/cp-ksqldb-server:7.3.0
    container_name: ksqldb
    depends_on:
      - kafka
      - schema-registry
    ports:
      - "8088:8088"
    environment:
      KSQL_KSQL_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      KSQL_BOOTSTRAP_SERVERS: kafka:29092
      KSQL_LISTENER_HTTP_PORT: 8088
      KSQL_KSQL_SERVICE_ID: "ksql"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: false
      KSQL_OPTS: "-Dconfluent.support.metrics.enable=false"
    mem_limit: '2g'

  multi-bank-system:
    image: sgg10/multi-bank-system
    container_name: multi-bank-system
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: bank-transactions
      KAFKA_GROUP_ID: bank-transactions-group
      KAFKA_CLIENT_ID: bank-transactions-client

  fraud-validator-api:
    hostname: fraud-validator-api
    image: sgg10/fraud-validator-api
    ports:
      - "8000:8000"

  transactions-ingestor:
    build:
      context: transactions-ingestor
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081

  unidentified-transactions-processor:
    build:
      context: unidentified-transactions-processor
    environment:
      KAFKA_BOOTSTRAP_SERVER: kafka:29092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      FRAUD_VALIDATOR_URL: http://fraud-validator-api:8000/validate
